### PR TITLE
Improve Travis CI build Performance

### PR DESCRIPTION
**Pull request by YunLemon**
Does travis_retry really solve the build issues? According to the data in paper [An empirical study of the long duration of continuous integration builds](https://dl.acm.org/doi/10.1007/s10664-019-09695-9), travis_retry can only solve 3% of the build failures. And it may cause unstable build and increase build time.

=====================
If there are any inappropriate modifications in this PR, please give me a reply and I will change them.

### CODE REVIEW

**Comment by leizhiyuan** [comment]
这个当时是为了部分用例会失败的问题，需要通过重试来解决。确实不够优雅。井盖找出flaky test ，并修复。这个跑一下看看一次性ci成功率

**Comment by YunLemon** [comment]
这个flaky test解决不了吗

**Comment by leizhiyuan** [comment]
> 这个flaky test解决不了吗

时间比较早了,不太记得当时是哪个,这个需要分析下。

**Comment by leizhiyuan** [comment]
> 这个flaky test解决不了吗

解决了 https://github.com/sofastack/sofa-rpc/pull/1074

麻烦merge一下master

**Comment by YunLemon** [comment]
merge 了

**Review by leizhiyuan — APPROVED** [review]
LGTM

**Comment by leizhiyuan** [comment]
> 这个flaky test解决不了吗

please sign a cla in http://cla.sofastack.tech/

**Comment by YunLemon** [comment]
> please sign a cla in http://cla.sofastack.tech/

签了

**Comment by leizhiyuan** [comment]
@OrezzerO  please
review and merge？

**Review by OrezzerO — APPROVED** [review]
LGTM

**Pull request merged**
