### PR TITLE
fix:fix simple map serializer

### PR DESCRIPTION
**Pull request by leizhiyuan**
### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification:

Describe the idea and modifications you've done.

### Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by khotyn** [comment]
Why there is no test case for a bug fix?

**Comment by leizhiyuan** [comment]
> Why there is no test case for a bug fix?

I will add a case for this.

**Comment by khotyn** [comment]
Is this bug fix related to issue #805 ?

**Comment by leizhiyuan** [comment]
> Is this bug fix related to issue #805 ?

yes

**Pull request merged**
