### PR TITLE
Change method name 'now' to 'getCurrentTime'

### PR DESCRIPTION
**Pull request by pdhung3012**
This class is used to represent   RpcRuntimeContext .  This method named 'now' is to get current time. Thus, the method name 'getCurrentTime' is more intuitive than 'now'.

### CODE REVIEW

**Comment by pdhung3012** [comment]
> Hi @pdhung3012, Please sign [Contributor License Agreement!](http://cla.sofastack.tech)
> 
> After you signed CLA, we will automatically sync the status of this pull request in 3 minutes.

Hello. I signed the CLA contract.

**Comment by JervyShi** [comment]
@pdhung3012 
This change is a non-compatible change. It is better to leave the original method and mark it as `@Deprecated` and bridge to the new method.

**Comment by pdhung3012** [comment]
> @pdhung3012
> This change is a non-compatible change. It is better to leave the original method and mark it as `@Deprecated` and bridge to the new method.

So that is it ok if I mark the now method as @Deprecate and create a new method getCurrentTime, then link the now method to getCurrentTime method?

Thanks

**Comment by leizhiyuan** [comment]
will not merge

**Pull request closed without merging**
