### PR TITLE
fix ProviderConfig setTimeout generic error

### PR DESCRIPTION
**Pull request by wind-hx**
### Motivation:

The result of calling setTimeout has no generic

### CODE REVIEW

**Comment by JervyShi** [comment]
@wind-hx Could you help fix similar problems in `ConsumerConfig`?

**Comment by wind-hx** [comment]
> @wind-hx Could you help fix similar problems in `ConsumerConfig`?

bug fixes

**Review by EvenLjj — APPROVED** [review]
LGTM

**Review by JervyShi — APPROVED** [review]
LGTM

**Comment by seeflood** [comment]
>2021-12-08 14:05:40,432 main ERROR [com.alipay.sofa.rpc.server.triple.TripleServer:error:187] - Register triple service error
java.lang.IllegalStateException: Can not expose service with same name:helloworld.Greeter


The error message in the integration tests is weird. 
This `helloworld.Greeter` was not modified in this PR.
@EvenLjj @OrezzerO Could you help check this problem?

**Comment by EvenLjj** [comment]
> > 2021-12-08 14:05:40,432 main ERROR [com.alipay.sofa.rpc.server.triple.TripleServer:error:187] - Register triple service error
> > java.lang.IllegalStateException: Can not expose service with same name:helloworld.Greeter
> 
> The error message in the integration tests is weird. This `helloworld.Greeter` was not modified in this PR. @EvenLjj @OrezzerO Could you help check this problem?

I will check this problem.

**Comment by EvenLjj** [comment]
@wind-hx @seeflood There were some problems in the previous unit test, and i will post a pr to solve this problem. This will be merged first, and finally thank you for participating.

**Comment by EvenLjj** [comment]
@wind-hx 
When this PR merge, the way to set ProviderConfig in method `setRef` will throw the exception `
capture of ?`. 

```
  RegistryConfig<?> config = new RegistryConfig();
  ServerConfig serverConfig = new ServerConfig();
  ProviderConfig<?> testServiceProviderConfig = new ProviderConfig<>();
  testServiceProviderConfig.setInterfaceId("TestService")
          .setUniqueId("unique123Id")
          .setApplication(new ApplicationConfig().setAppName("test-server"))
          .setProxy("javassist")
          .setRegister(true)
          .setRegistry(config)
          .setSerialization("hessian2")
          .setServer(serverConfig)
          .setWeight(222)
          .setTimeout(3000).setRef(new TestServiceImpl());
```

**Pull request merged**
