### PR TITLE
correct the comment for isRandomPort(). (#1256)

### LINKED ISSUE #1256: Confuse on the logic judge isRandomPort and the comment  note | 随机端口判断的逻辑和注释容易混淆
### Describe the bug

file-location : `sofa-rpc/core/api/src/main/java/com/alipay/sofa/rpc/common/utils/NetUtils.java`
function : `public static boolean isRandomPort(int port)`

logic in isRandomPort()  is conflict with the comment, so which is the correct ？ the logic or the comment ?

image
### Environment

- SOFARPC version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

### PR DESCRIPTION
**Pull request by jnan806**
Signed-off-by: Jiangnan Jia <<jnan0806@gmail.com>>

### Result:

Fixes #1256.

### CODE REVIEW

**Comment by jnan806** [comment]
@EvenLjj  It looks something wrong with `sofa-rpc-test-integration`, maybe some test cases make the workflow error.

**Comment by EvenLjj** [comment]
> @EvenLjj It looks something wrong with `sofa-rpc-test-integration`, maybe some test cases make the workflow error.

Yes, try again first.

**Review by EvenLjj — APPROVED** [review]
LGTM

**Review by OrezzerO — APPROVED** [review]
LGTM

**Pull request merged**
