### PR TITLE
Feat/add log

### PR DESCRIPTION
**Pull request by chuailiwu**
add log for serialize exception

### CODE REVIEW

**Review by JervyShi — CHANGES_REQUESTED** [review]
Any test cases for this PR?

**Comment by chuailiwu** [comment]
> Any test cases for this PR?

Added

**Review by OrezzerO — APPROVED** [review]
LGTM

**Review by JervyShi — APPROVED** [review]
LGTM

**Comment by EvenLjj** [comment]
image
@chuailiwu Please run `mvn clean compile -DskipTests` before you commit code, this will format the code.

**Comment by chuailiwu** [comment]
> 

done

**Pull request merged**
