### PR TITLE
add SofaRejectedExecutionHandler for  user-customized thread pool

### PR DESCRIPTION
**Pull request by bohrqiu**
### Motivation:

The bizExecutor of all servers (TripleServer, httpServer, BoltServer) are configured with `SofaRejectedExecutionHandler` for exception handling and log processing， but the user-customized thread pool is missing.

## Summary by CodeRabbit

- **New Features**
	- Introduced a custom handler for managing rejected tasks in the thread pool, improving task execution control.

- **Tests**
	- Added a new test to verify the functionality of the rejected execution handler in the thread pool.

### CODE REVIEW

**Comment by EvenLjj** [comment]
image
@bohrqiu Thank for your pr. Pls run `mvn clean compile` before git commit.

**Comment by bohrqiu** [comment]
@EvenLjj done

**Comment by EvenLjj** [comment]
@bohrqiu It's still the same problem.

**Comment by bohrqiu** [comment]
@EvenLjj oh sorry, i got it . i had format the code and run  `mvn clean install -Pci-install -B -U -e && bash ./tools/check_format.sh`

**Review by EvenLjj — APPROVED** [review]
LGTM

**Review by Lo1nt — APPROVED** [review]

**Pull request merged**
