### PR TITLE
improve script

### PR DESCRIPTION
**Pull request by oldratlee**
### Motivation:

improve script reliability

### Modification:

- use `bash` instead of `sh`
  more info or reason see Shell Style Guide of google:
  https://google.github.io/styleguide/shellguide.html#which-shell-to-use
- fix `shellcheck` warning
  - use `-z` instead of `! -n`
  - SC2086 Double quote to prevent globbing and word splitting
- check_format.sh
  - call `git status` one time

### CODE REVIEW

**Comment by oldratlee** [comment]
> Hi @oldratlee, welcome to SOFAStack community, Please sign [Contributor License Agreement!](http://cla.sofastack.tech)
> 
> After you signed CLA, we will automatically sync the status of this pull request in 3 minutes.

Sign Individual CLA need write all my user data(including Private email addresses, Private profile information),
this access seems ridiculous.

image

**Comment by nobodyiam** [comment]
@oldmee Thanks for your feedback, I agree with you and it looks like a mistaken configuration to me. We'll take a look and get back to you soon.

**Comment by seeflood** [comment]
@oldratlee You are right,there is no need to grant so much privilege and I will fix the robot.
You can sign cla with smaller scope by changing or removing the scope field in the url,like: https://github.com/login/oauth/authorize?client_id=1bd0989ae4b5298d11b5

(The raw url is https://github.com/login/oauth/authorize?client_id=1bd0989ae4b5298d11b5&scope=user,public_repo
and I removed the `scope` field )
This robot will read your email address.

**Comment by nobodyiam** [comment]
@oldratlee 

We checked the configuration and found the previous setup requires the `user` scope. However the bot only needs to read the user email as the contact information, so `user:email` scope should be enough. We just modified the configuration and it should be ok now.

> By the way, since the bot server is deployed in HangZhou, the signing process may occasionally time out, so please retry if this happens to you. We are planning to move the bot server to Hong Kong.

image

image

**Comment by oldratlee** [comment]
Thanks for your feedback, and I have signed the Individual CLA.

**Review by nobodyiam — APPROVED** [review]
LGTM

**Review by leizhiyuan — APPROVED** [review]
LGTM

**Pull request merged**
