### PR TITLE
Enable baggage-items for rpc reseteasy mode

### PR DESCRIPTION
**Pull request by chpengzh**
### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

 #663

### Modification:

Describe the idea and modifications you've done.

Fix bug 

### Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by chpengzh** [comment]
嗯，吃完宵夜回来看到构建还是queue状态...

**Comment by chpengzh** [comment]
A simple test demo is provided by https://gist.github.com/chpengzh/2d8aa34c0789819abb59502e6ed3b745

Try `curl http://localhost:8080\?name\=chpengzh`

**Comment by leizhiyuan** [comment]
Thanks for your contribution.
@chpengzh @JervyShi @leizhiyuan  please review it.

**Comment by chpengzh** [comment]
@leizhiyuan How's it going?

**Comment by ujjboy** [comment]
HI @chpengzh   can you add some test case for this change?

**Comment by chpengzh** [comment]
@ujjboy All right, I'll add some later.

**Comment by leizhiyuan** [comment]
Is there any update?

**Comment by chpengzh** [comment]
这个代码我是通过sofa-boot的用例去测试的，我不是很清楚这个单元测试应该如何加，能给点意见么

@leizhiyuan @ujjboy

**Comment by leizhiyuan** [comment]
> 这个代码我是通过sofa-boot的用例去测试的，我不是很清楚这个单元测试应该如何加。这个模块原本也缺少一些单元测试用例，请问能给一个简单的测试用例例子么。
> 
> @leizhiyuan @ujjboy

you can see com.alipay.sofa.rpc.server.rest.RestTest

**Comment by leizhiyuan** [comment]
@ujjboy @JervyShi @NeGnail  please review this change.

**Pull request merged**
