### PR TITLE
Clerical error

### PR DESCRIPTION
**Pull request by oldmee**
### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification:

Describe the idea and modifications you've done.

### Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by OrezzerO** [comment]
@oldmee  Thank you for your pr. Please sign Contributor License Agreement as above :)

**Comment by leizhiyuan** [comment]
麻烦签署一下cla，我们会尽快合并

**Comment by oldmee** [comment]
不好意思才看到，已经签署了

> 麻烦签署一下cla，我们会尽快合并

**Comment by leizhiyuan** [comment]
冲突需要解决下。无法通过页面解决。

 extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistry.java

**Comment by oldmee** [comment]
> 冲突需要解决下。无法通过页面解决。
> 
> 
> 
>  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistry.java 

是在master分支为基准么，我看了一下我之后这代码改过哇

**Comment by leizhiyuan** [comment]
> > 冲突需要解决下。无法通过页面解决。
> > extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistry.java
> 
> 是在master分支为基准么，我看了一下我之后这代码改过哇

嗯，是的，以master为准。把你的改动改上去。

**Pull request closed without merging**
